# Generated by Django 5.1.6 on 2025-05-16 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shift', models.CharField(max_length=1)),
                ('poste', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('role', models.CharField(choices=[('operateur', 'Opérateur'), ('logistique_incomming', 'Logistique_Incomming'), ('logistique_pagoda', 'Logistique_Pagoda'), ('logistique_kit', 'Logistique_Kit'), ('maintenance_machine', 'Maintenance_Machine'), ('maintenance_board', 'Maintenance_Board'), ('qualite', 'Qualité'), ('chef_equipe', "Chef d'équipe"), ('admin', 'Administrateur')], max_length=50)),
                ('zone', models.TextField(blank=True, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Alertechef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shift', models.CharField(max_length=1)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('traité', 'Traité')], default='en_attente', max_length=50)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('poste', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Alertemain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shift', models.CharField(max_length=1)),
                ('maintenance_type', models.CharField(blank=True, choices=[('maintenance_board', 'Maintenance Board'), ('maintenance_machine', 'Maintenance Machine')], max_length=50, null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('traité', 'Traité')], default='en_attente', max_length=50)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('poste', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Alertequal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shift', models.CharField(max_length=1)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('traité', 'Traité')], default='en_attente', max_length=50)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('poste', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shift', models.CharField(max_length=1)),
                ('type_machine', models.CharField(choices=[('soudage', 'Soudage'), ('sertissage', 'Sertissage')], max_length=100)),
                ('ident_type', models.CharField(blank=True, choices=[('V_ident', 'V_ident'), ('P_ident', 'P_ident')], max_length=20, null=True)),
                ('ident_code', models.CharField(blank=True, help_text='V_ident or P_ident code', max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('traité', 'Traité')], default='en_attente', max_length=50)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('poste', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Wire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident_code', models.CharField(help_text='V_ident or P_ident code (e.g., V56876485353)', max_length=50)),
                ('section', models.FloatField(help_text='Wire section (e.g., 0.2, 0.5, 1.0)')),
                ('length', models.FloatField(help_text='Wire length in meters')),
                ('color', models.CharField(help_text='Wire color', max_length=50)),
                ('position', models.CharField(help_text='Position (e.g., Two right, one left)', max_length=100)),
                ('barcode', models.CharField(blank=True, help_text='Unique barcode for the wire', max_length=50, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('ident_code', 'section', 'length', 'color', 'position')},
            },
        ),
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shift', models.CharField(max_length=1)),
                ('logistique_type', models.CharField(blank=True, choices=[('logistique_incomming', 'Logistique Incomming'), ('logistique_pagoda', 'Logistique Pagoda'), ('logistique_kit', 'Logistique Kit')], max_length=50, null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('traité', 'Traité')], default='en_attente', max_length=50)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('poste', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('wires', models.ManyToManyField(blank=True, help_text='Wires requested for this demande', to='kroschu_application.wire')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
