# Generated by Django 5.1.6 on 2025-02-27 09:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kroschu_application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alerte',
            name='type_alerte',
            field=models.CharField(choices=[('logistique', 'Logistique'), ('maintenance', 'Maintenance'), ('qualite', 'Qualité'), ('chef_equipe', "Chef d'équipe")], max_length=100),
        ),
        migrations.AlterField(
            model_name='demande',
            name='type_materiel',
            field=models.CharField(choices=[('fil', 'Fil'), ('gaine', 'Gaine'), ('terminale', 'Terminale'), ('connecteur', 'Connecteur')], max_length=100),
        ),
        migrations.AlterField(
            model_name='tache',
            name='type_machine',
            field=models.CharField(choices=[('soudage', 'Soudage'), ('sertissage', 'Sertissage'), ('coupage', 'Coupage')], max_length=100),
        ),
    ]
