# Generated by Django 5.1.6 on 2025-05-16 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kroschu_application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wire',
            name='barcode',
            field=models.CharField(default='TRT123456', help_text='Unique barcode for the wire', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
