# Generated by Django 5.1.6 on 2025-05-16 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kroschu_application', '0002_alter_wire_barcode'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wire',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='tache',
            name='version',
            field=models.CharField(default='v1', help_text='Version of the task (e.g., v1, v2)', max_length=10),
        ),
        migrations.AddField(
            model_name='wire',
            name='version',
            field=models.CharField(default='v1', help_text='Version of the wire (e.g., v1, v2)', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='wire',
            unique_together={('ident_code', 'section', 'length', 'color', 'position', 'version')},
        ),
    ]
