# Generated by Django 5.1.6 on 2025-02-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kroschu_application', '0003_alter_user_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerte',
            name='statut',
            field=models.CharField(choices=[('en_cours', 'En cours'), ('en_attente', 'En attente'), ('traite', 'Traité')], default='en_attente', max_length=50),
        ),
        migrations.AddField(
            model_name='demande',
            name='statut',
            field=models.CharField(choices=[('en_cours', 'En cours'), ('en_attente', 'En attente'), ('traite', 'Traité')], default='en_attente', max_length=50),
        ),
        migrations.AddField(
            model_name='tache',
            name='statut',
            field=models.CharField(choices=[('en_cours', 'En cours'), ('en_attente', 'En attente'), ('traite', 'Traité')], default='en_attente', max_length=50),
        ),
    ]
