# Generated by Django 5.1.6 on 2025-05-16 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kroschu_application', '0003_alter_wire_unique_together_tache_version_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tache',
            name='description',
        ),
    ]
