# Generated by Django 5.1.6 on 2025-02-27 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kroschu_application', '0004_alerte_statut_demande_statut_tache_statut'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Utilisateur',
        ),
    ]
