# Generated by Django 5.1.6 on 2025-05-17 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kroschu_application', '0004_remove_tache_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertequal',
            name='qualite_type',
            field=models.CharField(blank=True, choices=[('qualite_vk', 'Qualité VK'), ('qualite_cutting', 'Qualité Cutting '), ('qualite_ksk', 'Qualité KSK ')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('operateur', 'Opérateur'), ('logistique_incomming', 'Logistique_Incomming'), ('logistique_pagoda', 'Logistique_Pagoda'), ('logistique_kit', 'Logistique_Kit'), ('maintenance_machine', 'Maintenance_Machine'), ('maintenance_board', 'Maintenance_Board'), ('qualite_vk', 'Qualité_VK'), ('qualite_cutting', 'Qualité_Cutting'), ('qualite_ksk', 'Qualité_Ksk'), ('chef_equipe', "Chef d'équipe"), ('admin', 'Administrateur')], max_length=50),
        ),
    ]
