# Generated by Django 5.1.6 on 2025-02-27 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kroschu_application', '0005_rename_user_utilisateur'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Utilisateur',
            new_name='User',
        ),
    ]
