# Generated by Django 5.1.6 on 2025-05-17 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kroschu_application', '0005_alertequal_qualite_type_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertechef',
            name='chef_type',
            field=models.CharField(blank=True, choices=[('chef_vk', 'Chef VK'), ('chef_ksk', 'Chef KSK'), ('chef_cutting', 'Chef Cutting')], max_length=50, null=True),
        ),
    ]
