# Generated by Django 5.1.6 on 2025-05-17 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kroschu_application', '0006_alertechef_chef_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('operateur', 'Opérateur'), ('logistique_incomming', 'Logistique_Incomming'), ('logistique_pagoda', 'Logistique_Pagoda'), ('logistique_kit', 'Logistique_Kit'), ('maintenance_machine', 'Maintenance_Machine'), ('maintenance_board', 'Maintenance_Board'), ('qualite_vk', 'Qualité_VK'), ('qualite_cutting', 'Qualité_Cutting'), ('qualite_ksk', 'Qualité_Ksk'), ('chef_vk', 'Chef_VK'), ('chef_cutting', 'Chef_Cutting'), ('chef_ksk', 'Chef_Ksk'), ('admin', 'Administrateur')], max_length=50),
        ),
    ]
