# Generated by Django 5.1.6 on 2025-02-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kroschu_application', '0006_rename_utilisateur_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerte',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('traité', 'Traité')], default='en_attente', max_length=50),
        ),
        migrations.AlterField(
            model_name='demande',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('traité', 'Traité')], default='en_attente', max_length=50),
        ),
        migrations.AlterField(
            model_name='tache',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('traité', 'Traité')], default='en_attente', max_length=50),
        ),
    ]
