# Generated by Django 5.1.6 on 2025-05-21 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kroschu_application', '0007_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('operateur', 'Opérateur'), ('logistique_incomming', 'Logistique_Incomming'), ('logistique_pagoda', 'Logistique_Pagoda'), ('logistique_kit', 'Logistique_Kit'), ('maintenance_machine', 'Maintenance_Machine'), ('maintenance_board', 'Maintenance_Board'), ('qualite_vk', 'Qualité_VK'), ('qualite_cutting', 'Qualité_Cutting'), ('qualite_ksk', 'Qualité_Ksk'), ('chef_vk', 'Chef_VK'), ('chef_cutting', 'Chef_Cutting'), ('chef_ksk', 'Chef_Ksk'), ('admin', 'Administrateur'), ('polyvalent', 'Polyvalent')], max_length=50),
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('is_occupied', models.BooleanField(default=False)),
                ('current_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_machine', to='kroschu_application.tache')),
                ('queued_tasks', models.ManyToManyField(blank=True, related_name='queued_on_machine', to='kroschu_application.tache')),
            ],
        ),
        migrations.AddField(
            model_name='tache',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='kroschu_application.machine'),
        ),
    ]
