# Generated by Django 5.1.6 on 2025-02-28 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kroschu_application', '0009_user_is_active_user_is_admin_user_last_login_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
    ]
