# Generated by Django 5.1.6 on 2025-05-22 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kroschu_application', '0009_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='task_count',
            field=models.IntegerField(default=0),
        ),
    ]
