# Generated by Django 5.1.6 on 2025-05-23 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kroschu_application', '0010_machine_task_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='poste',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'operateur'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machines', to=settings.AUTH_USER_MODEL),
        ),
    ]
