# Generated by Django 5.1.6 on 2025-03-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kroschu_application', '0010_remove_user_is_active_remove_user_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerte',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demande',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
