# Generated by Django 5.1.6 on 2025-05-23 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kroschu_application', '0011_machine_poste'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wire',
            old_name='barcode',
            new_name='L_ident',
        ),
    ]
