# Generated by Django 5.1.6 on 2025-03-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kroschu_application', '0011_alerte_description_demande_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alerte',
            name='type_alerte',
        ),
        migrations.AddField(
            model_name='alerte',
            name='type_alerte_chef',
            field=models.CharField(choices=[('surplace', 'Surplace'), ('tacheterminer', 'Tacheterminer')], default='Surplace', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alerte',
            name='type_alerte_maintenance',
            field=models.CharField(choices=[('mecanique', 'Mécanique'), ('hydraulique', 'Hydraulique'), ('electrique', 'Électrique'), ('autre', 'Autre')], default='mecanique', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alerte',
            name='type_alerte_qualite',
            field=models.CharField(choices=[('verification', 'Verification'), ('validation', 'Validation')], default='verification', max_length=100),
            preserve_default=False,
        ),
    ]
