# Generated by Django 5.1.6 on 2025-03-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kroschu_application', '0012_remove_alerte_type_alerte_alerte_type_alerte_chef_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerte',
            name='type_alerte_chef',
            field=models.CharField(choices=[('assistance', 'Assistance'), ('autre', 'Autre')], max_length=100),
        ),
        migrations.AlterField(
            model_name='alerte',
            name='type_alerte_qualite',
            field=models.CharField(choices=[('verification', 'Verification'), ('validation', 'Validation'), ('autre', 'Autre')], max_length=100),
        ),
    ]
