# Generated by Django 5.1.6 on 2025-05-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kroschu_application', '0012_rename_barcode_wire_l_ident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wire',
            name='L_ident',
            field=models.CharField(max_length=50),
        ),
    ]
