# Generated by Django 5.1.6 on 2025-05-23 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kroschu_application', '0013_alter_wire_l_ident'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wire',
            unique_together=set(),
        ),
    ]
