# Generated by Django 5.1.6 on 2025-03-05 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kroschu_application', '0013_alter_alerte_type_alerte_chef_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alertechef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_alerte', models.CharField(choices=[('assistance', 'Assistance'), ('autre', 'Autre')], max_length=100)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('traité', 'Traité')], default='en_attente', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Alertemain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_alerte', models.CharField(choices=[('mecanique', 'Mécanique'), ('hydraulique', 'Hydraulique'), ('electrique', 'Électrique'), ('autre', 'Autre')], max_length=100)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('traité', 'Traité')], default='en_attente', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Alertequal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_alerte', models.CharField(choices=[('verification', 'Verification'), ('validation', 'Validation'), ('autre', 'Autre')], max_length=100)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('traité', 'Traité')], default='en_attente', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Alerte',
        ),
    ]
