# Generated by Django 5.1.6 on 2025-03-06 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kroschu_application', '0014_alertechef_alertemain_alertequal_delete_alerte'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alertemain',
            old_name='type_alerte',
            new_name='type_alertemain',
        ),
    ]
