# Generated by Django 5.1.6 on 2025-05-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kroschu_application', '0014_alter_wire_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='ident_type',
            field=models.CharField(blank=True, choices=[('V_ident', 'V_ident'), ('PM', 'PM')], max_length=20, null=True),
        ),
    ]
