# Generated by Django 5.1.6 on 2025-05-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kroschu_application', '0015_alter_tache_ident_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='ident_code',
            field=models.CharField(blank=True, help_text='V_ident or PM code', max_length=50, null=True),
        ),
    ]
