# Generated by Django 5.1.6 on 2025-03-06 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kroschu_application', '0015_rename_type_alerte_alertemain_type_alertemain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alertemain',
            old_name='user',
            new_name='user_id',
        ),
    ]
