# Generated by Django 5.1.6 on 2025-03-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kroschu_application', '0016_rename_user_alertemain_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alertechef',
            old_name='type_alerte',
            new_name='type_alertechef',
        ),
        migrations.RenameField(
            model_name='alertechef',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='alertequal',
            old_name='type_alerte',
            new_name='type_alertequal',
        ),
        migrations.RenameField(
            model_name='alertequal',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='tache',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
