# Generated by Django 5.1.6 on 2025-03-07 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kroschu_application', '0017_rename_type_alerte_alertechef_type_alertechef_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
