# Generated by Django 5.1.6 on 2025-03-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kroschu_application', '0018_demande_validated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demande',
            old_name='validated_at',
            new_name='date_traitement',
        ),
        migrations.AddField(
            model_name='demande',
            name='temps_ecoule',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
