# Generated by Django 5.1.6 on 2025-03-07 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kroschu_application', '0019_rename_validated_at_demande_date_traitement_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demande',
            old_name='date_traitement',
            new_name='finished_at',
        ),
    ]
