# Generated by Django 5.1.6 on 2025-03-10 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kroschu_application', '0021_remove_demande_finished_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
