# Generated by Django 5.1.6 on 2025-03-10 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kroschu_application', '0022_demande_validated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertechef',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alertemain',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alertequal',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tache',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
