# Generated by Django 5.1.6 on 2025-03-12 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kroschu_application', '0023_alertechef_validated_at_alertemain_validated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='nom',
            new_name='nom_prenom',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='prenom',
            new_name='poste',
        ),
        migrations.AddField(
            model_name='user',
            name='shift',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C')], default='A', max_length=50),
            preserve_default=False,
        ),
    ]
