# Generated by Django 5.1.6 on 2025-03-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kroschu_application', '0025_remove_demande_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='shift',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=50),
        ),
    ]
