# Generated by Django 5.1.6 on 2025-03-12 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kroschu_application', '0026_alter_user_shift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alertechef',
            name='description',
        ),
        migrations.RemoveField(
            model_name='alertechef',
            name='type_alertechef',
        ),
        migrations.RemoveField(
            model_name='alertemain',
            name='description',
        ),
        migrations.RemoveField(
            model_name='alertemain',
            name='type_alertemain',
        ),
        migrations.RemoveField(
            model_name='alertequal',
            name='description',
        ),
        migrations.RemoveField(
            model_name='alertequal',
            name='type_alertequal',
        ),
        migrations.AlterField(
            model_name='tache',
            name='type_machine',
            field=models.CharField(choices=[('soudage', 'Soudage'), ('sertissage', 'Sertissage')], max_length=100),
        ),
    ]
