# Generated by Django 5.1.6 on 2025-03-18 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kroschu_application', '0029_rename_user_id_alertechef_poste_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('operateur', 'Opérateur'), ('logistique', 'Logistique'), ('maintenance', 'Maintenance'), ('qualite', 'Qualité'), ('chef_equipe', "Chef d'équipe"), ('admin', 'Administrateur')], max_length=50),
        ),
    ]
