# Generated by Django 5.1.6 on 2025-03-18 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kroschu_application', '0034_user_is_active_user_is_staff_user_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
    ]
