# Generated by Django 5.1.6 on 2025-03-19 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kroschu_application', '0035_remove_user_is_active_remove_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('operateur', 'Opérateur'), ('logistique', 'Logistique'), ('maintenance', 'Maintenance'), ('qualite', 'Qualité'), ('chef_equipe', "Chef d'équipe")], max_length=50),
        ),
    ]
