# Generated by Django 5.1.6 on 2025-03-19 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kroschu_application', '0036_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('poste', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('role', models.CharField(choices=[('operateur', 'Opérateur'), ('logistique', 'Logistique'), ('maintenance', 'Maintenance'), ('qualite', 'Qualité'), ('chef_equipe', "Chef d'équipe"), ('admin', 'Administrateur')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='demande',
            name='poste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tache',
            name='poste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
