# Generated by Django 5.1.6 on 2025-03-24 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kroschu_application', '0041_alter_alertechef_poste_alter_alertemain_poste_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='description',
        ),
    ]
