# Generated by Django 5.1.6 on 2025-03-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kroschu_application', '0042_remove_user_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='zone',
            field=models.TextField(blank=True, null=True),
        ),
    ]
