# Generated by Django 5.1.6 on 2025-04-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kroschu_application', '0043_user_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='logistique_type',
            field=models.CharField(blank=True, choices=[('incomming', 'Logistique Incomming'), ('pagoda', 'Logistique Pagoda'), ('kit', 'Logistique Kit')], max_length=50, null=True),
        ),
    ]
