# Generated by Django 5.1.6 on 2025-04-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kroschu_application', '0045_alter_demande_logistique_type_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertemain',
            name='maintenance_type',
            field=models.CharField(blank=True, choices=[('maintenance_board', 'Maintenance Board'), ('maintenance_machine', 'Maintenance Machine')], max_length=50, null=True),
        ),
    ]
