# Generated by Django 5.1.6 on 2025-04-23 14:30

import kroschu_application.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kroschu_application', '0047_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertechef',
            name='shift',
            field=models.CharField(default=kroschu_application.models.determine_shift, editable=False, max_length=1),
        ),
        migrations.AddField(
            model_name='alertemain',
            name='shift',
            field=models.CharField(default=kroschu_application.models.determine_shift, editable=False, max_length=1),
        ),
        migrations.AddField(
            model_name='alertequal',
            name='shift',
            field=models.CharField(default=kroschu_application.models.determine_shift, editable=False, max_length=1),
        ),
        migrations.AddField(
            model_name='demande',
            name='shift',
            field=models.CharField(default=kroschu_application.models.determine_shift, editable=False, max_length=1),
        ),
    ]
