# Generated by Django 5.1.6 on 2025-04-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kroschu_application', '0048_alertechef_shift_alertemain_shift_alertequal_shift_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='shift',
            field=models.CharField(default='A', editable=False, max_length=1),
        ),
    ]
