# Generated by Django 5.1.6 on 2025-04-23 14:41

import kroschu_application.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kroschu_application', '0050_alter_alertechef_shift_alter_alertemain_shift_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertechef',
            name='shift',
            field=models.CharField(default=kroschu_application.models.determine_shift, editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='alertemain',
            name='shift',
            field=models.CharField(default=kroschu_application.models.determine_shift, editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='alertequal',
            name='shift',
            field=models.CharField(default=kroschu_application.models.determine_shift, editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='demande',
            name='shift',
            field=models.CharField(default=kroschu_application.models.determine_shift, editable=False, max_length=1),
        ),
    ]
