# Generated by Django 5.1.6 on 2025-04-23 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kroschu_application', '0051_alter_alertechef_shift_alter_alertemain_shift_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alertechef',
            name='shift',
        ),
        migrations.RemoveField(
            model_name='alertemain',
            name='shift',
        ),
        migrations.RemoveField(
            model_name='alertequal',
            name='shift',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='shift',
        ),
    ]
