# Generated by Django 5.1.6 on 2025-04-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kroschu_application', '0056_alter_alertechef_shift_alter_alertemain_shift_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shift',
            field=models.CharField(default='A', editable=False, max_length=1),
            preserve_default=False,
        ),
    ]
