# Generated by Django 5.1.6 on 2025-04-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kroschu_application', '0057_user_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertechef',
            name='shift',
            field=models.CharField(default='C', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='alertemain',
            name='shift',
            field=models.CharField(default='C', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='alertequal',
            name='shift',
            field=models.CharField(default='C', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='demande',
            name='shift',
            field=models.CharField(default='C', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='tache',
            name='shift',
            field=models.CharField(default='C', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='shift',
            field=models.CharField(default='C', editable=False, max_length=1),
        ),
    ]
