# Generated by Django 5.1.6 on 2025-04-24 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kroschu_application', '0064_alter_alertechef_shift_alter_alertemain_shift_and_more'),
    ]

    operations = [
    ]
